### ISSUE TITLE
Handbook refs update related to page template migration

### ISSUE THREAD

**Issue by tkrch** [Kentico/xperience-by-kentico-kentico-migration-tool#110]
Update [Handbook refs](https://github.com/Kentico/xperience-migration-toolkit/blob/master/Migration.Toolkit.CLI/MIGRATION_PROTOCOL_REFERENCE.md)

new references:
|Name|Severity|Description|
|---|---|---|
|NotSupportedSkip|Information|feature is not supported - for example migration of system class/resource that is not customizable|
|ErrorSavingTargetInstance|Error|Occurs when there is problem with persistence to target XbK database|

**Comment by DavidBKentico** [comment]
Added in pull request https://github.com/Kentico/xperience-migration-toolkit/pull/123.
