### ISSUE TITLE
since #103 order of commands doesn't matter (sort implemented)

### ISSUE THREAD

**Issue by tkrch** [Kentico/xperience-by-kentico-kentico-migration-tool#111]
Related doc issue:  #105

Order of migrate command arguments now doesn't matter.

These command executions will perform in same manner:
*  `migrate --siteId 1 --page-types --pages --forms --attachments --culture en-US  --sites  --users`

*  `migrate --siteId 1  --sites  --users --page-types --pages --forms --attachments --culture en-US `

*  `migrate --siteId 1  --sites  --pages --forms --attachments  --users --page-types --culture en-US `

**Comment by DavidBKentico** [comment]
No need to update the documentation. 

[https://github.com/Kentico/xperience-migration-toolkit/tree/master/Migration.Toolkit.CLI#migrate-data](https://github.com/Kentico/xperience-migration-toolkit/tree/master/Migration.Toolkit.CLI#migrate-data) describes the migrate command parameters, but we don't specify any order requirements.
