### ISSUE TITLE
Docs: Role & UserRole migration

### ISSUE THREAD

**Issue by tkrch** [Kentico/xperience-by-kentico-kentico-migration-tool#119]
New required version of Xperience by Kentico is **23.0.3**

In PR #117 new capabilities were added to command `migrate --users`

- Roles are migrated
- User Role relation is migrated along with Role and User

## Restrictions

* only roles with assigned user with administration privilege are migrated
* no public user is migrated - only users with administration access (`UserPrivilegeLevel > 0`)

**Comment by skurekjakub** [comment]
Opened #124 with documentation changes
