### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by ChristopherBass** [Kentico/xperience-by-kentico-kentico-migration-tool#169]
### Brief bug description

Upgrading Kentico.Xperience.AspNetCore.WebApp in the KX13.Extensions project to 13.0.128 or higher prevents compilation.  

### Repro steps

1. Open the Migration Toolkit in Visual Studio
2. Right click on the solution and pick "Manage Nuget Packages for Solution"
3. Go to "installed" and search for 'Xperience' 
4. See that the target version of Kentico.Xperience.AspNetCore.WebApp (and thus Kentico.Xperience.Libraries) for the "KX13.Extensions" project is '13.0.76
5. Site I want to migrate is 13.0.133, so we update that version.
6. Upgrading to 13.0.127 gives no errors, but going to 13.0.133 (or 13.0.128, or 13.0.147) throws a large set of compilation errors on ToolkitApiController, ranging from 'The name 'SiteContext' does not exist in the current context' to 'The type or namespace name 'Kentico' could not be found'

### Expected behavior

Migration code should be compileable using the versions of the APIs matching your source and target projects, or documentation should say to not try to match the 13 API's to the project version

### Test environment

 - .Net 8.0
 - No browser
 - Visual Studio 17.8.3

### Additional context

This started when I tried to run the site as-is on a KX13.0.133 -> XbyK 28.4.4 migration.
I got an error in the console that there was a version mismatch between 28.4.1 and 28.4.4, which led me to bumping up the XbyK APIs to 28.4.4.
I saw that the KX13 libraries were set to 13.0.76 (for KX13.Extensions) and 13.0.82 (for KX13.NET48.Extensions) so I wanted to get ahead of any issues by matching that to my repo as well.

I believe the issue is that .128 removed .net pre-6 support, and KX13.Extensions is marked for .net 5 and core 3.1 support. Removing those two from the Extensions project seems to get rid of the errors.

### Screenshot
https://imgur.com/S66ozNP

**Comment by liparova** [comment]
Thank you for reporting the issue. Our team will investigate it thoroughly and provide updates on the resolution.

**Comment by ChristopherBass** [comment]
Thank you - Just to be clear: If I'm migrating from a site that is
KX13.0.145 (or other new project) I should still keep the KX dependencies
in the Migration.Toolkit project itself as 13.0.82 and 13.0.74 (or whatever
they are), not alter the dependencies to match the version of KX13 I'm
using, correct? I know about the ToolkitApiController and putting it in my
source project, I just had assumed that the dependencies in the
Migration.Toolkit project itself should be altered to match. It may be
worth throwing some documentation in that api discovery setup setup step
(or anywhere) to say to leave that alone.
*_____________________*
Chris Bass
*Wakefly**,** Inc.*
