### ISSUE TITLE
Categories migration to taxonomy

### ISSUE THREAD

**Issue by tkrch** [Kentico/xperience-by-kentico-kentico-migration-tool#189]
documentation shall describe changes made in PR #188 

running command `--categories` will do migration of categories to taxonomy.

From this:
![image](https://github.com/Kentico/xperience-by-kentico-kentico-migration-tool/assets/23259342/349590ac-1e4b-40c3-8fef-99d3fe4d0971)

Becomes this:
![image](https://github.com/Kentico/xperience-by-kentico-kentico-migration-tool/assets/23259342/1a07b2e4-3a23-41a0-8e2d-a701b5780f77)

To support categories, MT needs to create field on each content type where categories are used.

field creation is achieved by reusable field schema:
![image](https://github.com/Kentico/xperience-by-kentico-kentico-migration-tool/assets/23259342/a3ea48f7-ee9a-4bfd-b15a-3f5caf024afe)
where field `Category_Legacy` exists
![image](https://github.com/Kentico/xperience-by-kentico-kentico-migration-tool/assets/23259342/c397c9ae-ce65-4661-bd3f-ef314c389cd3)

then can MT migrate tags into fields:
![image](https://github.com/Kentico/xperience-by-kentico-kentico-migration-tool/assets/23259342/ffc17969-0716-4027-bb72-68932280b6c8)

![image](https://github.com/Kentico/xperience-by-kentico-kentico-migration-tool/assets/23259342/0f7d9481-6e7a-4800-942e-1f65e3106480)

Side notes:
- categories are assigned to document without regards to version - XbyK works with taxonomy differently, tag can be assigned in draft but not in published content item version. MT tackles this by assigning to all versions
- categories are culture sensitive in relation to document culture version, MT respects this
- categories do not rely on page types, but taxonomy does. MT solves this by adding legacy field to all content types where category was used

Migration process:
1) MT ensures taxonomy `Categories` exists in target instance
2) MT finds all documents with categories and patches all produced content types in target instance (adds taxonomy field)
3) MT find all categories and starts migration of tags to taxonomy
4) MT performs for each tag search where is used and assignes selection of tags to target ContentItemCommonData

**Comment by DavidBKentico** [comment]
Someone will take a look at this as soon as possible. Task in the Kentico documentation backlog: https://kentico.atlassian.net/browse/DOC-2131
