### ISSUE TITLE
K12 user migration error

### ISSUE THREAD

**Issue by petrji** [Kentico/xperience-by-kentico-kentico-migration-tool#213]
### Brief bug description
Migrating Kentico 12 MVC to Xperience getting the error below.

Microsoft.EntityFrameworkCore.Database.Command[20102] Failed executing DbCommand (265ms) [Parameters=[@__PrivilegeLevelsMigratedAsAdminUser_0='?' (Size = 4000)], CommandType='Text', CommandTimeout='30'] SELECT [c].[UserID], [c].[Email], [c].[FirstName], [c].[FullName], [c].[LastLogon], [c].[LastName], [c].[MiddleName], [c].[PreferredCultureCode], [c].[PreferredUICultureCode], [c].[UserCreated], [c].[UserEnabled], [c].[UserGUID], [c].[UserHasAllowedCultures], [c].[UserIsDomain], [c].[UserIsExternal], [c].[UserIsHidden], [c].[UserLastLogonInfo], [c].[UserLastModified], [c].[UserMFRequired], [c].[UserMFSecret], [c].[UserMFTimestep], [c].[UserName], [c].[UserPassword], [c].[UserPasswordFormat], [c].[UserPrivilegeLevel], [c].[UserSecurityStamp], [c].[UserStartingAliasPath], [c].[UserVisibility] FROM [CMS_User] AS [c] WHERE [c].[UserPrivilegeLevel] IN (     SELECT [p].[value]     FROM OPENJSON(@__PrivilegeLevelsMigratedAsAdminUser_0) WITH ([value] int '$') AS [p] )
04:12:22.154 

### Repro steps

running Migration.Toolkit.CLI.exe migrate --sites --custom-modules --users

**Comment by liparova** [comment]
Hi! Thanks for sharing your problem and a solution! We'll take a look at it soon and consider adding it to the original integration.

**Comment by MilanLund** [comment]
@tkrch Getting the same error on K11 site. Hotfix v11.0.43. Here is the output:
![image](https://github.com/user-attachments/assets/4d407561-1a02-4ba8-a34d-aed8873dbe91)

**Comment by MilanLund** [comment]
@tkrch Following up on my previous comment, the issue is also present on the KX13 site I attempted to migrate. Logs are available here:
![image](https://github.com/user-attachments/assets/c7c038f0-6b90-4982-92e0-7796e551987e)
...
![image](https://github.com/user-attachments/assets/6399f6cb-c39c-42fc-92a4-0d76a8597521)

**Comment by MilanLund** [comment]
@tkrch Thanks for looking into this.
![image](https://github.com/user-attachments/assets/bf37b42c-5931-45ff-9535-fcb961d44f19)

**Comment by MilanLund** [comment]
@tkrch 
I attempted to migrate the K13 site. While the initial issue has been resolved, I encountered a new problem with Media Libraries and Attachments, which will require further investigation on my end.

As for the K11 site, I'm experiencing a similar issue, but with a different query. Here are logs:
![image](https://github.com/user-attachments/assets/388a2285-f8e4-4078-9189-1264df3cfc88)
...
![image](https://github.com/user-attachments/assets/0912d41b-6e80-4e9d-b6c8-372a73ca2d23)

**Comment by MilanLund** [comment]
@tkrch The issue is gone. Thank you. I came across another issue related to files missing in Media library but I guess that is something wrong on my end 😅.

**Comment by MilanLund** [comment]
@tkrch I'm missing these files on my end - I need to get the latest project files and database from the server. However, since I'm currently testing the migration tool to see if it's suitable for future projects, I am giving this a low priority for now.

**Comment by petrji** [comment]
Hi @tkrch,
I was on leave last week. Glad this has been resolved. BTW we are also experiencing issues with media libraries. Other dev may log new issue as I moved to other project. We are using Azure blob storage.
You can close this one now. Thanks
