### ISSUE TITLE
Random slugs append on tree paths causing invalid path references

### ISSUE THREAD

**Issue by purquhart** [Kentico/xperience-by-kentico-kentico-migration-tool#216]
The migration tool is appending a random slug to the tree path which makes all references invalid for items that we are retrieving by tree path. It also makes it so that you can't retrieve children via a certain tree path because it's children contain a different tree path. I noticed that we could modify the migration toolkit so that we could exclude the addition of that random slug - is this what we should do, or what is the recommended approach?

**Comment by purquhart** [comment]
For example using two original paths as follows:
/News
/News/XYZ

The tree path becomes the following on the migrated instance, so I think what is happening is that when you try to do a query via PathMatch.Children(treePath), it returns 0 results because the parent path is not even close to the parent path of the child.

/News-59uwibxb
/News/XYZ-6d8wydmp

**Comment by michalJakubis** [comment]
Hi @tkrch, yes this is standard behavior in XbK. The random suffix behind code name is being created every time you create new web page.

**Comment by purquhart** [comment]
Thanks @tkrch in seeing how things are working with the migration of paths, I think it's possible that this might fix itself once #217 is in place, I'll redo the migration later today or tomorrow with the update in place and get back to you.

**Comment by purquhart** [comment]
@tkrch the random slugs on the tree path are no longer happening as of the update you applied in #219, thank you.
