### ISSUE TITLE
Enable migrating resusable schema inheritance from base type inheritance

### ISSUE THREAD

**Issue by bluemodus-mwills** [Kentico/xperience-by-kentico-kentico-migration-tool#242]
### Motivation

Currently, the Migration Tool allows [migrating some types as reusable schemas](https://github.com/Kentico/xperience-by-kentico-kentico-migration-tool/blob/master/Migration.Toolkit.CLI/README.md#convert-page-types-to-reusable-field-schemas), but it doesn’t use the reusable schemas in the migrated derive types or content. 

### Proposed solution

To make it much more valuable, the migration would use the created reusable schemas in the migrated types, by detecting page types that inherit from the source base types, adding the reusable schemas to types in the target database, and using the reusable schema fields when migrating the content.

This could get complex, so the preferred solution would be to add this capability to the request in https://github.com/Kentico/xperience-by-kentico-kentico-migration-tool/issues/241. This would allow custom code to extend the migration tool and define which types should be migrated as reusable schema types, which reusable schema types should be inherited by other types, and which source fields should be mapped to new reusable schema type fields.

**Comment by seangwright** [comment]
This was also mentioned in #183

**Comment by bluemodus-mwills** [comment]
This is solved by the new Migration Tool Extensions feature, which allows creating a custom class mapping extension, which allows mapping multiple source types (and it's content) to a single target type. The mapping allows defining new fields, changing field names, skipping fields, changing data types, and using reusable schemas.

PR https://github.com/Kentico/xperience-by-kentico-kentico-migration-tool/pull/257

Readme: https://github.com/Kentico/xperience-by-kentico-kentico-migration-tool/blob/feat/238_ability_to_extend_migration/Migration.Tool.Extensions/README.md
