### ISSUE TITLE
Migration Tool only works on Windows, but Xperience is supported on Windows, macOS, and Linux

### ISSUE THREAD

**Issue by seangwright** [Kentico/xperience-by-kentico-kentico-migration-tool#256]
### Brief bug description

Although Kentico Xperience 13 ASPNET Core applications work on windows, linux, and macOS (via .NET 8) and Xperience by Kentico solutions also support the same operating systems, this migration tool is currently Windows-only.

This is because the [ConsoleHelper](https://github.com/Kentico/xperience-by-kentico-kentico-migration-tool/blob/v1.2.0/Migration.Toolkit.Common/Helpers/ConsoleHelper.cs#L15) class uses some DLL imports to Windows-only DLLs.

If we need the console output manipulation provided by this class we could use something like [Spectre Console](https://spectreconsole.net) instead so this migration tool could be run in non-Windows environments

### Repro steps

1. In a macOS or linux environment
1. Follow the setup instructions
2. Do a `dotnet build` in the `Migration.Toolkit.CLI` project
3. Run the executable in the `bin/Debug/net8.0` folder
4. See the following exception

```
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'kernel32.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: 
```

### Expected behavior

This tool works in all environments supported by Xperience by Kentico

### Test environment

 - Platform/OS: macOS M1
 - Browser Safari
 - Version 29.5.2

### Additional context

If I comment out [the code](https://github.com/Kentico/xperience-by-kentico-kentico-migration-tool/blob/v1.2.0/Migration.Toolkit.Common/Helpers/ConsoleHelper.cs#L24) in `EnableVirtualTerminalProcessing` then the migration tool works great in macOS.

### Screenshots

n/a

**Comment by Sapphirress** [comment]
Hi @seangwright, I have consulted this request with PM and our architects. Considering that, as tkrch writes, the Migration tool requires running source instance, we currently don't see this as a priority investment. If we see requests from the customers and partner agencies, we can open the issue again, but for now I am closing this one.
