### ISSUE TITLE
No asset item previews after migrating media library items to content hub assets

### ISSUE THREAD

**Issue by farmergeek94** [Kentico/xperience-by-kentico-kentico-migration-tool#299]
### Brief bug description

After migrating the media library items over to content hub assets the previews are not showing.

The assets load just fine but the previews are not being rendered out. 

### Repro steps

1. Go to the content hub 
2. Click on the smart folder of media (after creating it) 
3. View the rid view instead of the list view
4. None of the previews are pulling in.

### Expected behavior

The previews of the images should be shown. 

### Test environment

 - Platform/OS: .net 8 windows
 - Browser Chrome
 - Version 29.6.0

### Screenshots

![image](https://github.com/user-attachments/assets/cacfd6d6-35b6-429b-81a6-7e2ef2a403fe)

**Comment by akfakmot** [comment]
@farmergeek94 Issue fixed in Kentico.Xperience.UMT v1.10.1

**Comment by farmergeek94** [comment]
Thank you!!!
