### ISSUE TITLE
Documentation: orphaned page (without page type)

### ISSUE THREAD

**Issue by tkrch** [Kentico/xperience-by-kentico-kentico-migration-tool#84]
when page type gets removed from site, pages with that particular page type are left on site. That breaks migration constraint - only page types assigned to site are migrated, therefore page migration fails.

**How to resolve: assign page type back to migrated site**

Category: troubleshooting
Symptoms: migration toolkit will not find page class

**Comment by DavidBKentico** [comment]
Documented. Pull request created:
https://github.com/Kentico/xperience-migration-toolkit/pull/104
