### ISSUE TITLE
Documentation: Page template data migration / Page builder data migration advanced features

### ISSUE THREAD

**Issue by tkrch** [Kentico/xperience-by-kentico-kentico-migration-tool#89]
Optional feature - reading more information using kentico discovery from source instance (KX13).

In case of any questions related to feature contact @tkrch.
For any changes please use git branch `89-documentation-page-template-data-migration-page-builder-data-migration-advanced-features`
notes from DEV:

---

# Opt-in feature - QuerySourceInstanceApi

Toolkit needs to know for data  migation of widgets, sections, etc. what datatype/form component was used to store data. This information cannot be fetched from Kentico database. For example definition of widget, section, form component can be defined as class in source instance.  To overcome this issue, you can deploy this feature to enable toolkit migaration of such data.

### AspNetCore.Mvc

*  prerequisity ˙IHttpContextAccessor˙ must be configured. More information: https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.ihttpcontextaccessor?view=aspnetcore-6.0

1) copy `ToolkitApiController.cs` from `[ToolkitRoot]\KX13.Extensions` to `Controllers` directory of migrated Kentico Xperience 13 MVC Site

2)  Register controller route (registration is usually located in file `Startup.cs`  class `Startup`, method `Configure`, `app.UseEndpoints`)

```csharp
app.UseEndpoints(endpoints =>
{	
	endpoints.MapControllerRoute(
		name: "ToolkitExtendedFeatures",
		pattern: "{controller}/{action}",
		constraints: new
		{
			controller = "ToolkitApi"
		}
	);	
	
	// other routes ...
});
```

3)  Fill your secret inside `ToolkitApiController.cs`
```csharp
private const string Secret = "__your secret string__";
```

4) fill same secret in toolkit configuration path `Settings.OptInFeatures.QuerySourceInstanceApi.Connections[].Secret` like this:
```json
"OptInFeatures":{
  "QuerySourceInstanceApi": {
	"Enabled": false,
	"Connections": [
	  { "SourceInstanceUri": "http://localhost:60527", "Secret": "__your secret string__" }
	]
  }
},
```

5) *optional* You can test controller by making http POST request to `http://localhost:[port]/ToolkitApi/Test` with body `{ "secret":"__your secret string__" }`. Response should be `{ "pong": true }`

### AspNet.MVC5

1)  copy `ToolkitApiController.cs` from `[ToolkitRoot]\KX13.Extensions` to `Controllers` directory  of migrated Kentico Xperience 13 MVC Site
2)  Register controller route (usually located in `/App_Start/RouteConfig.cs`)

```csharp
public static void RegisterRoutes(RouteCollection routes)
{
	routes.MapRoute(
	   name: "ToolkitExtendedFeatures",
	   url: "{controller}/{action}",
	   defaults: new { },
	   constraints: new
	   {   
		   controller = "ToolkitApi"
	   }
	);
}
```

3)  Fill your secret inside `ToolkitApiController.cs`
```csharp
private const string Secret = "__your secret string__";
```

4) fill same secret in toolkit configuration path `Settings.OptInFeatures.QuerySourceInstanceApi.Connections[].Secret` like this:
```json
"OptInFeatures":{
  "QuerySourceInstanceApi": {
	"Enabled": false,
	"Connections": [
	  { "SourceInstanceUri": "http://localhost:60527", "Secret": "__your secret string__" }
	]
  }
},
```

5) *optional* You can test controller by making http POST request to `http://localhost:[port]/ToolkitApi/Test` with body `{ "secret":"__your secret string__" }`. Response should be `{ "pong": true }`

### Inlined value editor / component

Consider properties defined like this:
```csharp
public class CardWidgetProperties : IWidgetProperties
{
	
	public IEnumerable<MediaFilesSelectorItem> Image { get; set; } = new List<MediaFilesSelectorItem>();
	
	// ... other properties
	
}
```

and cshtml defined like this:
```razor
@if (Context.Kentico().PageBuilder().EditMode)
{
    <vc:image-uploader image-type="@ImageTypeEnum.MediaFile" property-name="@nameof(CardWidgetProperties.Image)"
                       has-image="@(Model.ImagePath != null)" message-position="@PanelPositionEnum.Top"
                       use-absolute-position="true" />
}
```
unfortunately this cannot be discovered using api - this type of data cannot be part migration. 

To overcome this issue, you can decorate such property with component explicitly:
```csharp
public class CardWidgetProperties : IWidgetProperties
{
	[EditingComponent(MediaFilesSelector.IDENTIFIER, Label = "Image", Order = 1)]
	public IEnumerable<MediaFilesSelectorItem> Image { get; set; } = new List<MediaFilesSelectorItem>();
	
	// ... other properties
	
}
```

**Comment by DavidBKentico** [comment]
Documented. Pull request created:
https://github.com/Kentico/xperience-migration-toolkit/pull/104
